### ISSUE TITLE
Update Guice Compatibility wiki page with GIN 3.0.0 and Guice 4.2.0

### ISSUE THREAD

**Issue by foal** [gwtplus/google-gin#9]
The project miss information what was changed since 2.1.

**Comment by foal** [comment]
I found this link https://github.com/gwtplus/google-gin/releases/tag/v3.0.0 But it will be really better to mention new release on the wiki page too.

**Comment by metteo** [comment]
Good catch. I will have to verify which new features were added in Guice 4.x and update the tables accordingly. In Gin v3 I didn't add any new features or fix bugs apart from those fixed automatically by using maven dependency resolution and upgraded dependencies.

**Comment by metteo** [comment]
Compatibility table was updated with new versions of Guice & Gin. There were no changes in features supported by Gin so I didn't add any new rows. They will be added when new feature is implemented or if a Guice feature is considered possible or not (P & N/A respectively)
